{
  "formatVersion": "1.1",
  "component": {
    "group": "com.clwater.plugin",
    "module": "Plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 5454,
          "sha512": "1a5a7e05c176b5ea8c840dcfcaa27c07a44c64a3d6f9bcc5044a343c47c8967ca60c25c599d6d792bcbfe7386d82be1ce422b2ea441b70c9c1a4c2d283f8cdab",
          "sha256": "514ae6ca3e2c540381838f8a3576650e360781b608d847e0134a1394b4c9cba0",
          "sha1": "85d1bd923f1182f07c836662673786c6aef857dc",
          "md5": "92764f1a068c56507b8573d850f77508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 5454,
          "sha512": "1a5a7e05c176b5ea8c840dcfcaa27c07a44c64a3d6f9bcc5044a343c47c8967ca60c25c599d6d792bcbfe7386d82be1ce422b2ea441b70c9c1a4c2d283f8cdab",
          "sha256": "514ae6ca3e2c540381838f8a3576650e360781b608d847e0134a1394b4c9cba0",
          "sha1": "85d1bd923f1182f07c836662673786c6aef857dc",
          "md5": "92764f1a068c56507b8573d850f77508"
        }
      ]
    }
  ]
}
